stages:
  - build
  - test
  - tests
  - deploy

Build:
  stage: build
  tags:
    - cat
    - grep
  script:
    - cd src/cat
    - make s21_cat
    - cd ../grep
    - make s21_grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days
  after_script:
    - cd src
    - bash telegram.sh

Style_Test:
  stage: test
  tags:
    - cat
    - grep
  script:
    - cd src/cat
    - clang-format -n --Werror *.c
    - cd ../grep
    - clang-format -n --Werror *.c
  after_script:
    - cd src
    - bash telegram.sh

Test:
  stage: tests
  tags:
    - cat
    - grep
  script:
    - cd src/cat
    - make test
    - cd ../grep
    - make test
  after_script:
    - cd src
    - bash telegram.sh


Deploy:
  stage: deploy
  tags:
    - cat
    - grep
  when: manual
  script:
    - cd src
    - bash copy.sh
  after_script:
    - cd src
    - bash telegram.sh
